CREATE TABLE `alpha_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidateId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL DEFAULT 'BTCUSDT',
	`direction` enum('LONG','SHORT') NOT NULL,
	`seedCondition` text,
	`confirmConditions` json,
	`fullExpression` text,
	`oosWinRate` float NOT NULL,
	`oosAvgReturn` float NOT NULL,
	`sampleSize` int DEFAULT 0,
	`icScore` float,
	`featureDimensions` json,
	`exitConditionTop3` json,
	`estimatedDailyTriggers` float DEFAULT 0,
	`confidenceScore` float DEFAULT 0,
	`overfitScore` float DEFAULT 0,
	`status` enum('pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
	`approvedAt` timestamp,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`discoveredAt` timestamp NOT NULL DEFAULT (now()),
	`backtestStatus` enum('idle','running','completed','failed') DEFAULT 'idle',
	`backtestResult` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alpha_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `alpha_candidates_candidateId_unique` UNIQUE(`candidateId`)
);
--> statement-breakpoint
CREATE TABLE `alpha_engine_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`status` enum('running','completed','failed','cancelled') NOT NULL DEFAULT 'running',
	`phase` enum('data_download','ic_scan','atom_mining','combo_scan','walk_forward','exit_mining','completed') NOT NULL DEFAULT 'data_download',
	`progress` int DEFAULT 0,
	`featuresScanned` int DEFAULT 0,
	`candidatesFound` int DEFAULT 0,
	`candidatesApproved` int DEFAULT 0,
	`icScanResults` json,
	`params` json,
	`errorMessage` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alpha_engine_runs_id` PRIMARY KEY(`id`),
	CONSTRAINT `alpha_engine_runs_runId_unique` UNIQUE(`runId`)
);
--> statement-breakpoint
CREATE TABLE `api_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`exchange` varchar(32) NOT NULL DEFAULT 'binance',
	`apiKey` varchar(256),
	`apiSecret` varchar(256),
	`isTestnet` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT false,
	`lastTestedAt` timestamp,
	`lastTestStatus` enum('success','failed','pending') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `api_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dev_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category` varchar(64) NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`status` enum('completed','in_progress','pending','blocked') NOT NULL DEFAULT 'pending',
	`priority` enum('critical','high','medium','low') NOT NULL DEFAULT 'medium',
	`layer` varchar(64),
	`completedAt` timestamp,
	`estimatedHours` float,
	`actualHours` float,
	`notes` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dev_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `strategies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`strategyId` varchar(64) NOT NULL,
	`name` varchar(128) NOT NULL,
	`type` enum('P1','P2','ALPHA') NOT NULL,
	`direction` enum('LONG','SHORT','BOTH') NOT NULL,
	`symbol` varchar(32) NOT NULL DEFAULT 'BTCUSDT',
	`entryCondition` text,
	`entryConditionJson` json,
	`exitConditionTop3` json,
	`oosWinRate` float,
	`oosAvgReturn` float,
	`isSampleSize` int DEFAULT 0,
	`oosSampleSize` int DEFAULT 0,
	`overfitScore` float DEFAULT 0,
	`featureDiversityScore` float DEFAULT 0,
	`confidenceScore` float DEFAULT 0,
	`triggerCount7d` int DEFAULT 0,
	`tradeCount7d` int DEFAULT 0,
	`pnl7d` decimal(20,8) DEFAULT '0',
	`totalTrades` int DEFAULT 0,
	`totalPnl` decimal(20,8) DEFAULT '0',
	`status` enum('active','paused','degraded','retired','pending') NOT NULL DEFAULT 'pending',
	`discoveredAt` timestamp DEFAULT (now()),
	`approvedAt` timestamp,
	`lastBacktestAt` timestamp,
	`backtestStatus` enum('idle','running','completed','failed') DEFAULT 'idle',
	`backtestResult` json,
	`params` json,
	`tags` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `strategies_id` PRIMARY KEY(`id`),
	CONSTRAINT `strategies_strategyId_unique` UNIQUE(`strategyId`)
);
--> statement-breakpoint
CREATE TABLE `system_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventType` enum('signal_triggered','trade_opened','trade_closed','alpha_discovered','alpha_approved','alpha_rejected','backtest_completed','system_error','system_warning','ws_connected','ws_disconnected','data_download_progress','engine_started','engine_stopped') NOT NULL,
	`symbol` varchar(32),
	`strategyId` varchar(64),
	`severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
	`title` varchar(256) NOT NULL,
	`message` text,
	`metadata` json,
	`isRead` boolean NOT NULL DEFAULT false,
	`occurredAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `system_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradeId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`strategyId` varchar(64),
	`direction` enum('LONG','SHORT') NOT NULL,
	`entryPrice` decimal(20,8) NOT NULL,
	`exitPrice` decimal(20,8),
	`quantity` decimal(20,8) NOT NULL,
	`leverage` int DEFAULT 1,
	`pnl` decimal(20,8),
	`pnlPercent` float,
	`fee` decimal(20,8) DEFAULT '0',
	`mfe` float,
	`mae` float,
	`exitReason` varchar(128),
	`exitConditionTriggered` varchar(256),
	`status` enum('open','closed','cancelled') NOT NULL DEFAULT 'open',
	`entryOrderId` varchar(64),
	`exitOrderId` varchar(64),
	`entryAt` timestamp NOT NULL,
	`exitAt` timestamp,
	`holdingMinutes` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trades_id` PRIMARY KEY(`id`),
	CONSTRAINT `trades_tradeId_unique` UNIQUE(`tradeId`)
);
--> statement-breakpoint
CREATE TABLE `trading_pairs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`baseAsset` varchar(16) NOT NULL,
	`quoteAsset` varchar(16) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`isTracked` boolean NOT NULL DEFAULT false,
	`dataCollectionStatus` enum('pending','downloading','completed','failed') NOT NULL DEFAULT 'pending',
	`dataDownloadProgress` int DEFAULT 0,
	`alphaEngineStatus` enum('idle','scanning','mining','completed','error') NOT NULL DEFAULT 'idle',
	`lastDataUpdate` timestamp,
	`totalKlines` bigint DEFAULT 0,
	`dataQualityScore` float DEFAULT 0,
	`currentPrice` decimal(20,8),
	`priceChange24h` float DEFAULT 0,
	`volume24h` decimal(30,8),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trading_pairs_id` PRIMARY KEY(`id`),
	CONSTRAINT `trading_pairs_symbol_unique` UNIQUE(`symbol`)
);
--> statement-breakpoint
CREATE TABLE `wallet_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`totalEquity` decimal(20,8),
	`availableBalance` decimal(20,8),
	`usedMargin` decimal(20,8),
	`unrealizedPnl` decimal(20,8),
	`assets` json,
	`snapshotAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wallet_snapshots_id` PRIMARY KEY(`id`)
);
